# This Docker compose file is modified from the example given in the
# official Ghost image by Docker on https://store.docker.com/images/ghost,
# integrating the work of the following devs:
#   - Adrian Perez (mariadb and Docker volumes): https://adrianperez.org/advanced-deployment-of-ghost-in-2-minutes-with-docker/
#   - Docker compose file reference (the Right Way™ to do volumes): https://docs.docker.com/compose/compose-file/#service-configuration-reference

version: '3.1'

services:
  ## Ghost blog container definition
  ghost:
    image: ghost:alpine
    container_name: deionarra
    restart: always
    environment:
      url: http://localhost
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
      ## Settings for reverse proxy and Let's Encrypt
      VIRTUAL_HOST: localhost
      LETSENCRYPT_HOST: example.com
      LETSENCRYPT_EMAIL: webmaster@example.com
    volumes:
      - legacy:/var/lib/ghost/content
    networks:
      - proxy
      - bridge
  ## Database container definition
  db:
    image: mysql:5.7
    container_name: mimir
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - mimir:/var/lib/mysql
    networks:
      - bridge
  ## Reverse-proxy container definitions
  nginx:
    image: nginx:alpine
    container_name: nginx
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - proxy:/etc/nginx/conf.d
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - proxy:/etc/nginx/certs:ro
      - proxy:/etc/nginx/htpasswd:ro
    networks:
      - proxy
  dockergen:
    image: jwilder/docker-gen
    container_name: proxy-gen
    command: -notify-sighup nginx -watch /etc/docker-gen/templates/nginx.tmpl /etc/nginx/conf.d/default.conf
    volumes:
      - /var/run/docker.sock:/tmp/docker.sock:ro
      - ./nginx.tmpl:/etc/docker-gen/templates/nginx.tmpl
      - proxy:/etc/nginx/conf.d
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - proxy:/etc/nginx/certs:ro
      - proxy:/etc/nginx/htpasswd:ro
    networks:
      - proxy
  ## Let's Encrypt
  letsencrypt-companion:
    image: jrcs/letsencrypt-nginx-proxy-companion
    container_name: letsencrypt-nginx-proxy-companion
    restart: always
    volumes:
      - proxy:/etc/nginx/conf.d
      - proxy:/etc/nginx/vhost.d
      - proxy:/usr/share/nginx/html
      - proxy:/etc/nginx/certs:rw
      - /var/run/docker.sock:/var/run/docker.sock:ro
    environment:
      NGINX_DOCKER_GEN_CONTAINER: proxy-gen
      NGINX_PROXY_CONTAINER: nginx
    networks:
      - proxy

volumes:
  legacy: ## Ghost data volume declaration
  mimir: ## Database data volume declaration
  proxy: ## Proxy data volume declaration

networks:
  bridge: ## Private bridge network declaration
  proxy: ## Public proxy network declaration
